initial version of multi-platform docker build
Co-authored-by: Alexander Rashed <alexander.rashed@localstack.cloud>

diff --git a/Dockerfile.stable b/Dockerfile.stable
--- a/Dockerfile.stable
+++ b/Dockerfile.stable
@@ -1,17 +1,41 @@
-FROM python:3.8-slim-buster as java-builder
+FROM python:3.8-slim-buster as base
 
 ARG TARGETOS
 ARG TARGETARCH
 
-# Install final dependencies
-RUN apt-get update && \
-        apt-get install -y --no-install-recommends \
-        openjdk-11-jdk-headless && \
-        apt-get clean && rm -rf /var/lib/apt/lists/*
+LABEL authors="LocalStack Contributors"
+LABEL maintainer="Waldemar Hummer (waldemar.hummer@gmail.com)"
+LABEL description="LocalStack Docker image"
+
+RUN apt-get update && apt-get install -y autoconf automake ca-certificates cmake curl libsasl2-dev \
+        g++ gcc git groff iputils-ping libffi-dev libkrb5-dev libtool make nss-passwords openssl libssl-dev \
+        postgresql postgresql-client postgresql-server-dev-11 libpq-dev postgresql-plpython3 tar pixz zip
+
+# Install Node 14.x
+RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
+RUN apt update && apt install -y nodejs
 
 SHELL [ "/bin/bash", "-c" ]
 
+# install Docker (CLI only)
+RUN DOCKER_VERSION=20.10.7; \
+  TARGETARCH_SYNONYM=$([[ "$TARGETARCH" == "amd64" ]] && echo "x86_64" || echo "aarch64"); \
+  curl -fsSLO https://download.docker.com/linux/static/stable/${TARGETARCH_SYNONYM}/docker-${DOCKER_VERSION}.tgz \
+  && tar xzvf docker-${DOCKER_VERSION}.tgz \
+  && mv docker/docker /usr/local/bin \
+  && rm -r docker docker-${DOCKER_VERSION}.tgz
+
+# Install Java 11
+ENV LANG C.UTF-8
+RUN { \
+        echo '#!/bin/sh'; echo 'set -e'; echo; \
+        echo 'dirname "$(dirname "$(readlink -f "$(which javac || which java)")")"'; \
+    } > /usr/local/bin/docker-java-home \
+    && chmod +x /usr/local/bin/docker-java-home
+
+RUN apt-get install -y openjdk-11-jdk-headless openjdk-11-jre-headless
 ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-${TARGETARCH}
+
 # create a custom, minimized JRE via jlink
 RUN jlink --add-modules \
 # include required modules
@@ -31,51 +55,8 @@ jdk.localedata --include-locales en,th \
   cp -r ${JAVA_HOME}/lib/* /usr/lib/jvm/java-11/lib/; \
   mv /usr/lib/jvm/java-11/lib/modules.bk /usr/lib/jvm/java-11/lib/modules; \
   rm -rf /usr/bin/java ${JAVA_HOME} && ln -s /usr/lib/jvm/java-11/bin/java /usr/bin/java
-
-
-
-FROM python:3.8-slim-buster as base
-
-ARG TARGETOS
-ARG TARGETARCH
-
-ARG LOCALSTACK_BUILD_DATE
-ARG LOCALSTACK_BUILD_GIT_HASH
-
-ENV LOCALSTACK_BUILD_DATE=${LOCALSTACK_BUILD_DATE}
-ENV LOCALSTACK_BUILD_GIT_HASH=${LOCALSTACK_BUILD_GIT_HASH}
-
-LABEL authors="LocalStack Contributors"
-LABEL maintainer="Waldemar Hummer (waldemar.hummer@gmail.com)"
-LABEL description="LocalStack Docker image"
-
-# Install final dependencies
-RUN apt-get update && \
-        # Setup Node 14 Dependencies
-        apt-get install -y --no-install-recommends curl && \
-        curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
-        # Install Packages
-        apt-get update && \
-        apt-get install -y --no-install-recommends \
-        git make nodejs openssl tar pixz zip unzip && \
-        apt-get clean && rm -rf /var/lib/apt/lists/*
-
-SHELL [ "/bin/bash", "-c" ]
-
-# Install Java 11
-ENV LANG C.UTF-8
-RUN { \
-        echo '#!/bin/sh'; echo 'set -e'; echo; \
-        echo 'dirname "$(dirname "$(readlink -f "$(which javac || which java)")")"'; \
-    } > /usr/local/bin/docker-java-home \
-    && chmod +x /usr/local/bin/docker-java-home
-
-
-COPY --from=java-builder /usr/lib/jvm/java-11 /usr/lib/jvm/java-11
-COPY --from=java-builder /etc/ssl/certs/java /etc/ssl/certs/java
-COPY --from=java-builder /etc/java-11-openjdk/security /etc/java-11-openjdk/security
-RUN ln -s /usr/lib/jvm/java-11/bin/java /usr/bin/java
 ENV JAVA_HOME /usr/lib/jvm/java-11
+ENV ES_JAVA_HOME /usr/lib/jvm/java-11
 ENV PATH "${PATH}:${JAVA_HOME}/bin"
 
 # Install Maven - taken from official repo:
@@ -98,6 +79,9 @@ ADD https://raw.githubusercontent.com/carlossg/docker-maven/master/openjdk-11/se
 RUN mkdir -p /opt/code/localstack
 WORKDIR /opt/code/localstack/
 
+# https://github.com/pires/docker-elasticsearch/issues/56
+ENV ES_TMPDIR /tmp
+
 # install npm dependencies
 ADD localstack/package.json localstack/package.json
 RUN cd localstack && npm install && rm -rf /root/.npm;
@@ -114,57 +98,9 @@ RUN mkdir -p /opt/code/localstack/localstack/infra && \
     curl -L -o /tmp/elasticmq-server.jar \
         https://s3-eu-west-1.amazonaws.com/softwaremill-public/elasticmq-server-1.1.0.jar
 
-# final fixes
-RUN which python || ln -s /usr/bin/python3 /usr/bin/python
-
-# install basic tools to final image
-RUN pip install awscli-local requests --upgrade
-
-# install supervisor config file and entrypoint script
-ADD bin/supervisord.conf /etc/supervisord.conf
-ADD bin/docker-entrypoint.sh /usr/local/bin/
-
-# expose default environment
-# Set edge bind host so localstack can be reached by other containers
-# set library path and default LocalStack hostname
-ENV MAVEN_CONFIG=/opt/code/localstack \
-    LD_LIBRARY_PATH=/usr/lib/jvm/java-11/lib:/usr/lib/jvm/java-11/lib/server \
-    USER=localstack \
-    PYTHONUNBUFFERED=1 \
-    EDGE_BIND_HOST=0.0.0.0 \
-    LOCALSTACK_HOSTNAME=localhost
-
-RUN mkdir /root/.serverless; chmod -R 777 /root/.serverless
-
-# add trusted CA certificates to the cert store
-RUN curl https://letsencrypt.org/certs/letsencryptauthorityx3.pem.txt >> /etc/ssl/certs/ca-certificates.crt
-
-# expose edge service, ElasticSearch & debugpy ports
-EXPOSE 4566 4571 5678
-
-# define command at startup
-ENTRYPOINT ["docker-entrypoint.sh"]
-
-
-FROM base as base-arm64
-# Work around crashes in Kenesis with error -11
-# https://github.com/localstack/localstack/issues/4358
-ENV KINESIS_PROVIDER=kinesalite
-
-
-FROM base as base-amd64
-ENV KINESIS_PROVIDER=kinesis-mock
-
-
-FROM base-${TARGETARCH} as builder
-
-# Install build dependencies to base
-RUN apt-get update && apt-get install -y autoconf automake cmake libsasl2-dev \
-        g++ gcc libffi-dev libkrb5-dev libssl-dev \
-        postgresql-server-dev-11 libpq-dev
-
 # installing terraform temporary - removed in the final docker image
-ARG TERRAFORM_ZIP_URL=https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_${TARGETARCH}.zip
+# TODO: Remove $PATH variable from the final docker image
+ARG TERRAFORM_ZIP_URL=https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_linux_${TARGETARCH}.zip
 RUN mkdir -p /opt/terraform && \
     curl -L -o /opt/terraform/terraform.zip ${TERRAFORM_ZIP_URL} && \
     (cd /opt/terraform && unzip -q /opt/terraform/terraform.zip && rm /opt/terraform/terraform.zip)
@@ -183,8 +119,43 @@ RUN (pip3 install --upgrade pip) && \
 # install libs that require dependencies that are cleaned up below (e.g., gcc)
 RUN (virtualenv .venv && source .venv/bin/activate && pip install 'cryptography<3.4' 'uamqp>=1.2.14' 'coverage[toml]>=5.5')
 
-# install basic tools for build
-RUN pip install awscli --upgrade
+# final fixes
+RUN which python || ln -s /usr/bin/python3 /usr/bin/python
+
+
+
+FROM base as base-arm64
+# Work around crashes in Kenesis with error -11
+# https://github.com/localstack/localstack/issues/4358
+ENV KINESIS_PROVIDER=kinesalite
+
+
+
+FROM base as base-amd64
+ENV KINESIS_PROVIDER=kinesis-mock
+
+
+
+FROM base-${TARGETARCH} as light
+
+LABEL authors="LocalStack Contributors"
+LABEL maintainer="Waldemar Hummer (waldemar.hummer@gmail.com)"
+
+ARG LOCALSTACK_BUILD_DATE
+ARG LOCALSTACK_BUILD_GIT_HASH
+
+ENV LOCALSTACK_BUILD_DATE=${LOCALSTACK_BUILD_DATE}
+ENV LOCALSTACK_BUILD_GIT_HASH=${LOCALSTACK_BUILD_GIT_HASH}
+
+# set library path and default LocalStack hostname
+ENV LD_LIBRARY_PATH=/usr/lib/jvm/java-11/lib:/usr/lib/jvm/java-11/lib/server
+ENV LOCALSTACK_HOSTNAME=localhost
+
+# Set edge bind host so localstack can be reached by other containers
+ENV EDGE_BIND_HOST=0.0.0.0
+
+# install basic tools
+RUN pip install awscli awscli-local requests --upgrade
 
 # upgrade python build tools
 RUN (virtualenv .venv && source .venv/bin/activate && pip install --upgrade pip wheel setuptools localstack-plugin-loader)
@@ -204,40 +175,20 @@ RUN make freeze > requirements-runtime.txt
 ADD localstack/infra/stepfunctions localstack/infra/stepfunctions
 RUN make init
 
+# install supervisor config file and entrypoint script
+ADD bin/supervisord.conf /etc/supervisord.conf
+ADD bin/docker-entrypoint.sh /usr/local/bin/
+
+# expose default environment
+ENV MAVEN_CONFIG=/opt/code/localstack \
+    USER=localstack \
+    PYTHONUNBUFFERED=1
+
 # clean up and prepare for squashing the image
 RUN pip uninstall -y awscli boto3 botocore localstack_client idna s3transfer
-RUN rm -rf .venv/lib/python3.*/site-packages/cfnlint
-RUN (virtualenv .venv && source .venv/bin/activate && pip cache purge)
-# RUN rm -rf /tmp/* /root/.cache /opt/yarn-* /root/.npm/*cache
-
-FROM base-${TARGETARCH} as light
-
-# Install runtime dependences to base
-RUN apt-get update && \
-        # Install dependencies to get Docker
-        apt-get install -y --no-install-recommends ca-certificates curl gnupg lsb-release && \
-        curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
-        echo \
-            "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
-            $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
-        # Install Runtime Packages
-        apt-get update && \
-        apt-get install -y --no-install-recommends \
-            # Install latest version of Docker-CLI
-            docker-ce-cli \
-            # Required for AWS CLI Help
-            groff-base \
-            iputils-ping \
-            nss-passwords \
-            postgresql \
-            postgresql-client \
-            postgresql-plpython3
-
-# Copy in the build dependences
-COPY --from=builder /opt/code/localstack /opt/code/localstack
-
-RUN mkdir -p /tmp/localstack && \
-    if [ -e /usr/bin/aws ]; then mv /usr/bin/aws /usr/bin/aws.bk; fi; ln -s /opt/code/localstack/.venv/bin/aws /usr/bin/aws
+RUN rm -rf /usr/share/maven .venv/lib/python3.*/site-packages/cfnlint
+RUN rm -rf /tmp/* /root/.cache /opt/yarn-* /root/.npm/*cache; mkdir -p /tmp/localstack
+RUN if [ -e /usr/bin/aws ]; then mv /usr/bin/aws /usr/bin/aws.bk; fi; ln -s /opt/code/localstack/.venv/bin/aws /usr/bin/aws
 
 # set up PYTHONPATH (after global pip packages are removed above), accommodating different install paths
 ENV PYTHONPATH=/opt/code/localstack/.venv/lib/python3.9/site-packages:/opt/code/localstack/.venv/lib/python3.8/site-packages:/opt/code/localstack/.venv/lib/python3.7/site-packages
@@ -253,16 +204,28 @@ RUN mkdir -p /.npm && \
     # chown -R localstack:localstack . /tmp/localstack && \
     ln -s `pwd` /tmp/localstack_install_dir
 
+# add trusted CA certificates to the cert store
+RUN curl https://letsencrypt.org/certs/letsencryptauthorityx3.pem.txt >> /etc/ssl/certs/ca-certificates.crt
+
+# clean up packages from build
+RUN apt-get autoremove --purge -y autoconf automake cmake git gcc g++ libtool libffi-dev libkrb5-dev libsasl2-dev libssl-dev \
+      postgresql-server-dev-11 libpq-dev; \
+    rm -rf /tmp/localstack/*elasticsearch* /tmp/localstack.* tests/ /root/.npm/*cache /opt/terraform /root/.serverless; \
+    rm -rf .pytest_cache/; \
+    mkdir /root/.serverless; chmod -R 777 /root/.serverless
+
+# expose edge service, ElasticSearch & debugpy ports
+EXPOSE 4566 4571 5678
+
+# define command at startup
+ENTRYPOINT ["docker-entrypoint.sh"]
+
 
 
 FROM light as full
 
 # Install Elasticsearch
-# https://github.com/pires/docker-elasticsearch/issues/56
-ENV ES_TMPDIR /tmp
-
 ENV ES_BASE_DIR=localstack/infra/elasticsearch
-ENV ES_JAVA_HOME /usr/lib/jvm/java-11
 RUN TARGETARCH_SYNONYM=$([[ "$TARGETARCH" == "amd64" ]] && echo "x86_64" || echo "aarch64"); \
     curl -L -o /tmp/localstack.es.tar.gz \
         https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.7.0-linux-${TARGETARCH_SYNONYM}.tar.gz && \
